version: "3.7"
services:

  app:
    build:
      dockerfile: docker/app.Dockerfile
      context: .
    container_name: app
    ports:
      - "8000:${APP_PORT}"
    volumes:
      - ./:/home/code/app
    