"""empty message

Revision ID: 44092824386c
Revises: 1475ad158bc0
Create Date: 2023-12-10 07:23:59.748916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44092824386c'
down_revision: Union[str, None] = '1475ad158bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('category_id', sa.UUID(), nullable=False))
    op.drop_constraint('comments_announcement_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'categories', ['category_id'], ['id'])
    op.drop_column('comments', 'announcement_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('announcement_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_announcement_id_fkey', 'comments', 'announcements', ['announcement_id'], ['id'])
    op.drop_column('comments', 'category_id')
    # ### end Alembic commands ###
